### Реєстрація
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Тест Другий",
  "email": "test2@test.com",
  "password": "12345",
  "role": "student"
}

### Вхід
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "12345"
}

### Список техніки (усі)
GET http://localhost:3000/api/equipment

### Список техніки з фільтром
GET http://localhost:3000/api/equipment?category=camera&status=available

### Одна одиниця техніки
GET http://localhost:3000/api/equipment/1

### Додати техніку (вставити токен адміна після Send Request на логін адміна)
POST http://localhost:3000/api/equipment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc5MDkzODA1MSwiZXhwIjoxNzkxNTQyODUxfQ.wxGXo5_uwVo4lDNB0ikn_qAj-zLZdBH15wYQ5cv11A0

{
  "name": "Nikon D5600",
  "category": "camera",
  "inventoryNumber": "INV-009",
  "description": "Дзеркальна камера для фотогуртка"
}

### Вхід адміна
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "oleh@example.com",
  "password": "password123"
}